# client.properties ? ??t trong bidhub-client/src/main/resources/
# C?u hình k?t n?i ??n server

# ??a ch? IP c?a server(??i sang IP th?t khi demo v?i máy khác)
server.host=localhost

# Ph?i kh?p v?i server.port trong bidhub-server/src/main/resources/server.properties
server.port=9090